---
title: Data Sources
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Title of your vignette}
  \usepackage[UTF-8]{inputenc}
---

# HydroData Data Repositories

HydroData offers access to 17 data sources. Details can be found at the following: 

## Gridded Data

- The [ USDA Cropland Layer Dataset](https://www.nass.usda.gov/Research_and_Science/Cropland/SARS1a.php) from 1997:2017 when/where available
- The [ USGS National Elevation Dataset (NED)](http://ned.usgs.gov) elevation data at 1 and 1/3 arc-second
- The [ Daymet V3](https://daymet.ornl.gov/) gridded and point estimates of daily weather parameters
- The [ National Land Cover Database (NLCD)](https://www.mrlc.gov/) from 2001, 2006, and 2011
- The [ PRISM monthly and Annual Normal Datasets](http://prism.oregonstate.edu) from Oregon State
- The [ Koppen Climate Classifation Dataset](http://koeppen-geiger.vu-wien.ac.at/present.htm) 

## Vector Data

- The [ USGS GAGESII dataset](https://water.usgs.gov/GIS/metadata/usgswrd/XML/gagesII_Sept2011.xml)
- The [ USGS National Hydrography Flowline Network (NHD)](http://nhd.usgs.gov) 
- The [ USGS National Hydrography Waterbody Network (NHD)](http://nhd.usgs.gov) 
- The [ USGS Network-Linked Data Index](https://cida.usgs.gov/nldi/about) 
- The [ US Army Corps National Dam Inventory](https://catalog.data.gov/dataset/national-inventory-of-dams)
- The [ Watershed Boundary Dataset](https://nhd.usgs.gov/userGuide/Robohelpfiles/NHD_User_Guide/Feature_Catalog/Watershed_Boundary_Dataset/Watershed_Boundary_Dataset.htm) at all levels from 2 to 12
- The [ TIGER road network dataset](https://www.census.gov/geo/maps-data/data/tiger.html)
- The [ USGS Water Use Dataset](https://water.usgs.gov/watuse/) for 2005, 2010, and 2015 

## Observation Station Networks

- The [ USGS National Water Information System (NWIS)](https://nwis.waterdata.usgs.gov/nwis) stream gages
- The [ Global Historical Climatology Network (GHCN)](http://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/global-historical-climatology-network-ghcn),
- The [ SNOTEL station inventory](https://www.wcc.nrcs.usda.gov/snow/)
- The [ Openflights Airport Database](https://openflights.org/data.html)
- The [ Applied Climate Information System](http://www.rcc-acis.org)
- The [ Automated Surface Observing System](https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/automated-surface-observing-system-asos)
- The [ NOAA Normals](https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/climate-normals/1981-2010-normals-data)
- The [ U.S. Climate Reference Network](https://www.ncdc.noaa.gov/crn/)
  
 
 
  


   
