---
pagetitle: HydroData for R
---

```{r echo = FALSE, results='hide', warning=FALSE,message=FALSE}
devtools::load_all()
library(kableExtra)
```

##Getting Observation Data 

```{r echo = FALSE, message = FALSE}
text_tbl <- data.frame(
`Stations` = c("WeatherUnderground", "Global Historic Climatology Network", "Snow Telemetry", "National Water Information System", "Water Use"),
 Source = c("WeatherUnderground", "NOAA", "NRCS", "USGS", "USGS"),
 Function = c("getWU( )", "getGHCN( )", "getUSGS( )", "getSnotel( )", "getWaterUse( )" )
) 

rownames(text_tbl) = paste0(c(1:5), ".")

text_tbl$Function <- cell_spec(text_tbl$Function, background ="lightgray", color = "black")


kable(text_tbl, escape = F, format = "html") %>%
   kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```


### Get GHCN Observation Data

```{r, message = FALSE}
ghcn = findGHCN(clip_unit = list("UCSB", 10, 10), param = "TMIN", ids = T)
data = getGHCN(IDs = ghcn$ids[1])
str(data, max = 1)
```

```{r, echo = FALSE}
kable(tail(data$TMIN, 10)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### Get Snotel meterological and snow pack data

```{r}
snow = findSnotel(state = "CA", county = "Modoc", ids = T)
data = getSnotel(IDs = snow$ids[1])
```

```{r, echo = FALSE}
kable(head(data)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### ### Get USGS Gages Information from NWIS server

```{r, message = FALSE}
usgs = findUSGS(clip_unit = list("UCSB", 10, 10), ids = T)
flow = getUSGS(IDs = usgs$ids)
```

```{r, echo = FALSE}
kable(tail(flow)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

### Get Airport based WeatherUnderground Data

```{r, message=FALSE}
ap = findAirports(clip_unit = list("UCSB", 10, 10), ids = T)
weather = getWU(IDs = ap$ids[1], year = 2017)
```

```{r, echo = FALSE}
kable(head(weather)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%      scroll_box(width = "100%", height = "200px")
```

### Get USGS County Water Use data

```{r, message = F}
use = waterUse(state = "CA", county = "Santa Barbara", year = 2010)
```

```{r, echo = FALSE}
kable(head(use$data)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```


