---
pagetitle: HydroData for R
---

```{r echo = FALSE, results='hide', warning=FALSE,message=FALSE}
devtools::load_all()
library(kableExtra)
```

##Getting Vector Data 

```{r echo = FALSE}
text_tbl <- data.frame(
Data = c("National Hydrography Dataset Stream Networks", "National Hydrography Watershed Boundary", "Global Waterbodies", "TIGER Road Networks"),
 Source = c("USGS/EPA", "USGS/EPA", "ESRI", "US Census"),
 Function = c("getNHD( )", "getHUC( )", "getWaterbodies( )", "getRoads( )")
) 

rownames(text_tbl) = paste0(c(1:4), ".")

text_tbl$Function <- cell_spec(text_tbl$Function, background ="lightgray", color = "black")

kable(text_tbl, escape = F, format = "html") %>%
   kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```

###Getting National Hydrography Dataset Flowlines

```{r, message=FALSE}
nhd = findNHD(clip_unit = list("UCSB", 10, 10))
str(nhd, max = 1)
```

```{r, echo = FALSE}
explore(nhd)
```


### National Hydrography Dataset Watershed Boundaries

```{r}
huc10 = findHUC(clip_unit = list("UCSB", 10, 10))
str(nhd, max = 1)
```

```{r}
explore(huc10)
```

### Get World Waterbodies

The polygons represent the open water rivers, lakes, seas, and oceans of the world.

```{r, message= FALSE}
wb = findWaterbodies(clip_unit = list("UCSB", 20, 20))
str(wb, max = 1)
```

```{r, echo = FALSE}
explore(wb)
```

### Get US Census TIGER Road Networks

```{r, message = FALSE}
tiger = findRoads(clip_unit = list("UCSB", 10, 10))
str(tiger, max = 1)
```

```{r, echo = FALSE}
explore(tiger)
```


