
wu_index = data.frame(

  ids = c("STATE",      "STATEFIPS",  "COUNTY",     "COUNTYFIPS", "FIPS",     "TP.TotPop",  "PS.GWPop",   "PS.SWPop",   "PS.TOPop",   "PS.WGWFr",
        "PS.WGWSa",   "PS.WGWTo",   "PS.WSWFr",   "PS.WSWSa",   "PS.WSWTo",   "PS.WFrTo",   "PS.WSaTo",   "PS.Wtotl",   "DO.SSPop",   "DO.WGWFr",   "DO.WSWFr",
        "DO.WFrTo",   "DO.SSPCp",   "DO.PSDel",   "DO.PSPCp",   "DO.TOTAL",   "IN.WGWFr",   "IN.WGWSa",   "IN.WGWTo",   "IN.WSWFr",   "IN.WSWSa",   "IN.WSWTo",
        "IN.WFrTo",   "IN.WSaTo",   "IN.Wtotl",   "IR.WGWFr",   "IR.WSWFr",   "IR.WFrTo",   "IR.IrSpr",   "IR.IrMic",   "IR.IrSur",   "IR.IrTot",   "IC.WGWFr",
        "IC.WSWFr",   "IC.WFrTo",   "IC.IrSpr",   "IC.IrMic",   "IC.IrSur",   "IC.IrTot",   "IG.WGWFr",   "IG.WSWFr",   "IG.WFrTo",   "IG.IrSpr",   "IG.IrMic",
        "IG.IrSur",   "IG.IrTot",   "LI.WGWFr",   "LI.WSWFr",   "LI.WFrTo",   "AQ.WGWFr",   "AQ.WGWSa",   "AQ.WGWTo",   "AQ.WSWFr",   "AQ.WSWSa",   "AQ.WSWTo",
        "AQ.WFrTo",   "AQ.WSaTo",   "AQ.WTotl",   "MI.WGWFr",   "MI.WGWSa",   "MI.WGWTo",   "MI.WSWFr",   "MI.WSWSa",   "MI.WSWTo",   "MI.WFrTo",   "MI.WSaTo",
        "MI.Wtotl",   "PT.WGWFr",   "PT.WGWSa",   "PT.WGWTo",   "PT.WSWFr",   "PT.WSWSa",   "PT.WSWTo",   "PT.WFrTo",   "PT.WSaTo",   "PT.Wtotl",  "PT.Power",
        "PO.WGWFr",   "PO.WGWSa",   "PO.WGWTo",   "PO.WSWFr",   "PO.WSWSa",   "PO.WSWTo",   "PO.WFrTo",   "PO.WSaTo",   "PO.WTotl",   "PO.Power",   "PC.WGWFr",
        "PC.WGWSa",   "PC.WGWTo",   "PC.WSWFr",   "PC.WSWSa",   "PC.WSWTo",   "PC.WFrTo",   "PC.WSaTo",   "PC.WTotl",   "PC.Power",   "TO.WGWFr",   "TO.WGWSa",
        "TO.WGWTo",   "TO.WSWFr",   "TO.WSWSa",   "TO.WSWTo",   "TO.WFrTo",   "TO.WSaTo",   "TO.WTotl"),

  full.names = c("State postal abbreviation",
          "State FIPS code",
          "County name",
          "County FIPS code",
          "Concatenated state-county FIPS code",
          "Total population of county, in thousands",
          "Public Supply, population served by groundwater, in thousands",
          "Public Supply, population served by surface water, in thousands",
          "Public Supply, total population served, in thousands",
          "Public Supply, groundwater withdrawals, fresh, in Mgal/d",
          "Public Supply, groundwater withdrawals, saline, in Mgal/d",
          "Public Supply, groundwater withdrawals, total, in Mgal/d",
          "Public Supply, surface-water withdrawals, fresh, in Mgal/d",
          "Public Supply, surface-water withdrawals, saline, in Mgal/d",
          "Public Supply, surface-water withdrawals, total, in Mgal/d",
          "Public Supply, total withdrawals, fresh, in Mgal/d",
          "Public Supply, total withdrawals, saline, in Mgal/d",
          "Public Supply, total withdrawals, total (fresh+saline), in Mgal/d",
          "Domestic, self-supplied population, in thousands",
          "Domestic, self-supplied groundwater withdrawals, fresh, in Mgal/d",
          "Domestic, self-supplied surface-water withdrawals, fresh, in Mgal/d",
          "Domestic, total self-supplied withdrawals, fresh, in Mgal/d",
          "Domestic self-supplied per capita use, in gallons/day [DO-WFrTo/DO-SSPop*1000]",
          "Domestic, deliveries from Public Supply, in Mgal/d",
          "Domestic, publicly supplied per capita use, in gallons/day [DO-PSDel/PS-TOPop]",
          "Domestic, total use (withdrawals + deliveries)",
          "Industrial, self-supplied groundwater withdrawals, fresh, in Mgal/d",
          "Industrial, self-supplied groundwater withdrawals, saline, in Mgal/d",
          "Industrial, self-supplied groundwater withdrawals, total, in Mgal/d",
          "Industrial, self-supplied surface-water withdrawals, fresh, in Mgal/d",
          "Industrial, self-supplied surface-water withdrawals, saline, in Mgal/d",
          "Industrial, self-supplied surface-water withdrawals, total, in Mgal/d",
          "Industrial, self-supplied total withdrawals, fresh, in Mgal/d",
          "Industrial, self-supplied total withdrawals, saline, in Mgal/d",
          "Industrial, self-supplied total withdrawals, total (fresh+saline), in Mgal/d",
          "Irrigation, groundwater withdrawals, fresh, in Mgal/d",
          "Irrigation, surface-water withdrawals, fresh, in Mgal/d",
          "Irrigation, total withdrawals, fresh, in Mgal/d",
          "Irrigation, acres irrigated, sprinkler, in thousands",
          "Irrigation, acres irrigated, microirrigation, in thousands",
          "Irrigation, acres irrigated, surface (flood), in thousands",
          "Irrigation, acres irrigated, total, in thousands",
          "Irrigation-Crop, groundwater withdrawals, fresh, in Mgal/d",
          "Irrigation-Crop, surface-water withdrawals, fresh, in Mgal/d",
          "Irrigation-Crop, total withdrawals, fresh, in Mgal/d",
          "Irrigation-Crop, acres irrigated, sprinkler, in thousands",
          "Irrigation-Crop, acres irrigated, microirrigation, in thousands",
          "Irrigation-Crop, acres irrigated, surface (flood), in thousands",
          "Irrigation-Crop, acres irrigated, total, in thousands",
          "Irrigation-Golf, groundwater withdrawals, fresh, in Mgal/d",
          "Irrigation-Golf, surface-water withdrawals, fresh, in Mgal/d",
          "Irrigation-Golf, total withdrawals, fresh, in Mgal/d",
          "Irrigation-Golf, acres irrigated, sprinkler, in thousands",
          "Irrigation-Golf, acres irrigated, microirrigation, in thousands",
          "Irrigation-Golf, acres irrigated, surface (flood), in thousands",
          "Irrigation-Golf, acres irrigated, total, in thousands",
          "Livestock, groundwater withdrawals, fresh, in Mgal/d",
          "Livestock, surface-water withdrawals, fresh, in Mgal/d",
          "Livestock, total withdrawals, fresh, in Mgal/d",
          "Aquaculture, groundwater withdrawals, fresh, in Mgal/d",
          "Aquaculture, groundwater withdrawals, saline, in Mgal/d",
          "Aquaculture, groundwater withdrawals, total, in Mgal/d",
          "Aquaculture, surface-water withdrawals, fresh, in Mgal/d",
          "Aquaculture, surface-water withdrawals, saline, in Mgal/d",
          "Aquaculture, surface-water withdrawals, total, in Mgal/d",
          "Aquaculture, total withdrawals, fresh, in Mgal/d",
          "Aquaculture, total withdrawals, saline, in Mgal/d",
          "Aquaculture, total withdrawals, total (fresh+saline), in Mgal/d",
          "Mining, groundwater withdrawals, fresh, in Mgal/d",
          "Mining, groundwater withdrawals, saline, in Mgal/d",
          "Mining, groundwater withdrawals, total, in Mgal/d",
          "Mining, surface-water withdrawals, fresh, in Mgal/d",
          "Mining, surface-water withdrawals, saline, in Mgal/d",
          "Mining, surface-water withdrawals, total, in Mgal/d",
          "Mining, total withdrawals, fresh, in Mgal/d",
          "Mining, total withdrawals, saline, in Mgal/d",
          "Mining, total withdrawals, total (fresh+saline), in Mgal/d",
          "Thermoelectric, groundwater withdrawals, fresh, in Mgal/d",
          "Thermoelectric, groundwater withdrawals, saline, in Mgal/d",
          "Thermoelectric, groundwater withdrawals, total, in Mgal/d",
          "Thermoelectric, surface-water withdrawals, fresh, in Mgal/d" ,
          "Thermoelectric, surface-water withdrawals, saline, in Mgal/d",
          "Thermoelectric, surface-water withdrawals, total, in Mgal/d",
          "Thermoelectric, total withdrawals, fresh, in Mgal/d",
          "Thermoelectric, total withdrawals, saline, in Mgal/d",
          "Thermoelectric, total withdrawals, total (fresh+saline), in Mgal/d",
          "Thermoelectric, power generated, in gigawatt-hours",
          "Thermoelectric once-through, groundwater withdrawals, fresh, in Mgal/d",
          "Thermoelectric once-through, groundwater withdrawals, saline, in Mgal/d",
          "Thermoelectric once-through, groundwater withdrawals, total, in Mgal/d",
          "Thermoelectric once-through, surface-water withdrawals, fresh, in Mgal/d",
          "Thermoelectric once-through, surface-water withdrawals, saline, in Mgal/d",
          "Thermoelectric once-through, surface-water withdrawals, total, in Mgal/d",
          "Thermoelectric once-through, total withdrawals, fresh, in Mgal/d",
          "Thermoelectric once-through, total withdrawals, saline, in Mgal/d",
          "Thermoelectric once-through, total withdrawals, total, in Mgal/d",
          "Thermoelectric once-through, power generated, in gigawatt-hours",
          "Thermoelectric recirculation, groundwater withdrawals, fresh, in Mgal/d",
          "Thermoelectric recirculation, groundwater withdrawals, saline, in Mgal/d",
          "Thermoelectric recirculation, groundwater withdrawals, total, in Mgal/d",
          "Thermoelectric recirculation, surface-water withdrawals, fresh, in Mgal/d",
          "Thermoelectric recirculation, surface-water withdrawals, saline, in Mgal/d",
          "Thermoelectric recirculation, surface-water withdrawals, total, in Mgal/d",
          "Thermoelectric recirculation, total withdrawals, fresh, in Mgal/d",
          "Thermoelectric recirculation, total withdrawals, saline, in Mgal/d",
          "Thermoelectric recirculation, total withdrawals, total (fresh+saline), in Mgal/d",
          "Thermoelectric recirculation, power generated, in gigawatt-hours",
          "Total groundwater withdrawals, fresh, in Mgal/d",
          "Total groundwater withdrawals, saline, in Mgal/d",
          "Total groundwater withdrawals, total (fresh+saline), in Mgal/d",
          "Total surface-water withdrawals, fresh, in Mgal/d",
          "Total surface-water withdrawals, saline, in Mgal/d",
          "Total surface-water withdrawals, total (fresh+saline), in Mgal/d",
          "Total withdrawals, fresh, in Mgal/d",
          "Total withdrawals, saline, in Mgal/d",
          "Total withdrawals, total (fresh+saline), in Mgal/d"),

    stringsAsFactors = FALSE)


wu.variable = data.frame(matrix(ncol=length(wu_index$full.names), nrow = 0))
colnames(wu.variable) = wu_index$full.names
wu.variable[1,] = wu_index$full.names






